spring:
  datasource:
    url: jdbc:mysql://localhost:3306/contest_manager?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 100101

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create